import type { AppConfig } from './types'

// Default configuration that reproduces the source spreadsheet exactly.
// The Settings page deep-clones this for "Reset to defaults".
export const DEFAULT_CONFIG: AppConfig = {
  statutory: {
    deMinimis: 3700,
    sssRate: 0.1,
    sssMaxMSC: 35000,
    sssEC: 30,
    philhealthRate: 0.025,
    philhealthFloor: 10000,
    philhealthCeiling: 100000,
    pagibig: 200,
    hmo: 1775,
    fcfRate: 0.03,
    feeRounding: 50,
    thirteenthDivisor: 12,
  },
  shifts: { Day: 0.0, Mid: 0.015, Late: 0.2 },
  regions: {
    NZD: { symbol: 'NZ$', exchRate: 34, bpo: 1045, benefits: 120, it: 100, factor: 1.0, cpd: 0 },
    AUD: { symbol: 'AU$', exchRate: 37, bpo: 995, benefits: 120, it: 100, factor: 1.0, cpd: 0 },
    USD: { symbol: 'US$', exchRate: 52, bpo: 820, benefits: 120, it: 100, factor: 1.125, cpd: 0 },
    CAD: { symbol: 'CA$', exchRate: 40, bpo: 1050, benefits: 120, it: 100, factor: 1.125, cpd: 0 },
    GBP: { symbol: '£', exchRate: 65, bpo: 550, benefits: 50, it: 50, factor: 1.0, cpd: 0 },
  },
  extras: [
    { name: 'Kick Start Programme', NZD: 4470, AUD: 4470, USD: 375, CAD: 750, GBP: 0, type: 'add' },
    { name: 'Graduate Programme', NZD: 1000, AUD: 1000, USD: 750, CAD: 1000, GBP: 0, type: 'add' },
    { name: 'HMO for Dependants', NZD: 100, AUD: 100, USD: 75, CAD: 100, GBP: 50, type: 'add' },
    { name: 'Travel Subsidy - Within Hour (12-20 days)', NZD: 30, AUD: 30, USD: 20, CAD: 30, GBP: 30, type: 'add' },
    { name: 'Travel Subsidy - Within Hour (<=11 days)', NZD: 15, AUD: 15, USD: 10, CAD: 15, GBP: 15, type: 'add' },
    { name: 'Travel Subsidy - Outside an Hour (12-20 days)', NZD: 60, AUD: 60, USD: 40, CAD: 60, GBP: 60, type: 'add' },
    { name: 'Travel Subsidy - Outside an Hour (<=11 days)', NZD: 30, AUD: 30, USD: 20, CAD: 30, GBP: 30, type: 'add' },
    { name: 'Accommodation Subsidy', NZD: 100, AUD: 100, USD: 70, CAD: 100, GBP: 50, type: 'add' },
    { name: 'Sign-on Bonus (one-off)', NZD: 0, AUD: 0, USD: 0, CAD: 0, GBP: 0, type: 'add' },
    { name: 'Non-CPA Discount (if applies)', NZD: -50, AUD: -50, USD: -35, CAD: -50, GBP: -30, type: 'nonCpaDiscount' },
  ],
  roles: [
    { category: 'Accounting', role: 'Graduate – Non Regularised', gross: 30000 },
    { category: 'Accounting', role: 'Graduate – Regularised', gross: 35000 },
    { category: 'Accounting', role: 'Junior Accountant – L1', gross: 40000 },
    { category: 'Accounting', role: 'Junior Accountant – L2', gross: 45000 },
    { category: 'Accounting', role: 'Intermediate Accountant – L1', gross: 50000 },
    { category: 'Accounting', role: 'Intermediate Accountant – L2', gross: 60000 },
    { category: 'Accounting', role: 'Intermediate Accountant – L3', gross: 70000 },
    { category: 'Accounting', role: 'Senior Accountant – L1', gross: 80000 },
    { category: 'Accounting', role: 'Senior Accountant – L2', gross: 95000 },
    { category: 'Accounting', role: 'Senior Accountant – L3', gross: 110000 },
    { category: 'Accounting', role: 'Team Leader – Small Team', gross: 75000 },
    { category: 'Accounting', role: 'Team Leader – Large Team', gross: 95000 },
    { category: 'Accounting', role: 'Accounting Manager', gross: 122500 },
    { category: 'Accounting', role: 'Senior Accounting Manager', gross: 140000 },
    { category: 'Tax', role: 'Tax Associate – L1 (Local Experience)', gross: 45000 },
    { category: 'Tax', role: 'Tax Associate – L2 (Local Experience)', gross: 50000 },
    { category: 'Tax', role: 'Tax Associate – L3 (Local Experience)', gross: 60000 },
    { category: 'Tax', role: 'Tax Associate – L1 (International Experience)', gross: 80000 },
    { category: 'Tax', role: 'Tax Associate – L2 (International Experience)', gross: 100000 },
    { category: 'Tax', role: 'Tax Associate – L3 (International Experience)', gross: 120000 },
    { category: 'Tax', role: 'Tax Senior – L1', gross: 150000 },
    { category: 'Tax', role: 'Tax Senior – L2', gross: 170000 },
    { category: 'Tax', role: 'Tax Senior – L3', gross: 190000 },
    { category: 'Tax', role: 'Tax Team Lead', gross: 220000 },
    { category: 'Tax', role: 'Tax Manager', gross: 250000 },
    { category: 'Bookkeeping', role: 'Bookkeeper – Entry (0 exp)', gross: 30000 },
    { category: 'Bookkeeping', role: 'Bookkeeper – L1', gross: 40000 },
    { category: 'Bookkeeping', role: 'Bookkeeper – L2', gross: 50000 },
    { category: 'Bookkeeping', role: 'Bookkeeper – L3', gross: 60000 },
    { category: 'Bookkeeping', role: 'Senior Bookkeeper', gross: 75000 },
    { category: 'Bookkeeping', role: 'Master Bookkeeper', gross: 92500 },
    { category: 'Virtual Assistant', role: 'Virtual Assistant – Entry (0 exp)', gross: 30000 },
    { category: 'Virtual Assistant', role: 'Virtual Assistant – L1', gross: 40000 },
    { category: 'Virtual Assistant', role: 'Virtual Assistant – L2', gross: 50000 },
    { category: 'Virtual Assistant', role: 'Virtual Assistant – L3', gross: 60000 },
    { category: 'Virtual Assistant', role: 'Virtual Assistant – L4', gross: 70000 },
    { category: 'Virtual Assistant', role: 'Virtual Assistant – L5', gross: 90000 },
    { category: 'Marketing', role: 'Marketing Assistant – Entry (0 exp)', gross: 30000 },
    { category: 'Marketing', role: 'Marketing Assistant – L1', gross: 40000 },
    { category: 'Marketing', role: 'Marketing Assistant – L2', gross: 50000 },
    { category: 'Marketing', role: 'Marketing Assistant – L3', gross: 60000 },
    { category: 'Marketing', role: 'Marketing Assistant – L4', gross: 70000 },
    { category: 'Marketing', role: 'Marketing Assistant – L5', gross: 90000 },
    { category: 'Marketing', role: 'Specialized Marketing', gross: 115000 },
    { category: 'Marketing', role: 'Digital Marketing Specialist – L1', gross: 55000 },
    { category: 'Marketing', role: 'Digital Marketing Specialist – L2', gross: 80000 },
    { category: 'Marketing', role: 'Digital Marketing Specialist – L3', gross: 110000 },
    { category: 'IT / Technology', role: 'IT / Web Technician – Entry (0 exp)', gross: 35000 },
    { category: 'IT / Technology', role: 'IT / Web Technician – L1', gross: 40000 },
    { category: 'IT / Technology', role: 'IT / Web Technician – L2', gross: 50000 },
    { category: 'IT / Technology', role: 'IT / Web Technician – L3', gross: 60000 },
    { category: 'IT / Technology', role: 'IT / Web Technician – L4', gross: 70000 },
    { category: 'IT / Technology', role: 'IT / Web Technician – L5', gross: 83000 },
    { category: 'IT / Technology', role: 'Specialized IT / Web Technician', gross: 120000 },
    { category: 'IT / Technology', role: 'IT Recruiter – L1', gross: 45000 },
    { category: 'IT / Technology', role: 'IT Recruiter – L2', gross: 50000 },
    { category: 'IT / Technology', role: 'IT Recruiter – L3', gross: 65000 },
    { category: 'IT / Technology', role: 'Full Stack Developer – L1', gross: 75000 },
    { category: 'IT / Technology', role: 'Full Stack Developer – L2', gross: 125000 },
    { category: 'IT / Technology', role: 'Full Stack Developer – L3', gross: 175000 },
    { category: 'Engineering & Architecture', role: 'Draftsman – L1', gross: 45000 },
    { category: 'Engineering & Architecture', role: 'Draftsman – L2', gross: 50000 },
    { category: 'Engineering & Architecture', role: 'Draftsman – L3', gross: 65000 },
    { category: 'Engineering & Architecture', role: 'Architect – L1', gross: 55000 },
    { category: 'Engineering & Architecture', role: 'Architect – L2', gross: 65000 },
    { category: 'Engineering & Architecture', role: 'Architect – L3', gross: 80000 },
    { category: 'Engineering & Architecture', role: 'Engineer – L1', gross: 55000 },
    { category: 'Engineering & Architecture', role: 'Engineer – L2', gross: 65000 },
    { category: 'Engineering & Architecture', role: 'Engineer – L3', gross: 80000 },
    { category: 'Analyst', role: 'AML Analyst – L1', gross: 50000 },
    { category: 'Analyst', role: 'AML Analyst – L2', gross: 55000 },
    { category: 'Analyst', role: 'AML Analyst – L3', gross: 60000 },
    { category: 'Analyst', role: 'AML Analyst – L4', gross: 65000 },
    { category: 'Analyst', role: 'AML Analyst – L5', gross: 70000 },
  ],
}
